# Generated by Django 3.2.13 on 2022-06-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='currency',
            field=models.CharField(default='USD', max_length=100, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='provider',
            name='language',
            field=models.CharField(default='English', max_length=100, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.provider', verbose_name='Provider'),
        ),
    ]
