# Generated by Django 3.2.13 on 2022-06-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_servicearea_polygon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicearea',
            old_name='polygon',
            new_name='geom',
        ),
    ]
